Update scripts to partition disks

diff --git a/tinypxe/roles/system_files_create/templates/opt/iolite-build.sh.j2 b/tinypxe/roles/system_files_create/templates/opt/iolite-build.sh.j2
--- a/tinypxe/roles/system_files_create/templates/opt/iolite-build.sh.j2
+++ b/tinypxe/roles/system_files_create/templates/opt/iolite-build.sh.j2
@@ -1,4 +1,5 @@
 #!/bin/sh
+set -e
 
 getIp4() {
 	echo $(/sbin/ip -o a | /usr/bin/awk '/'$DEV' *inet /{split($4, a, "/"); print a[1]}')
@@ -22,15 +23,12 @@ rebootSystem() {
 	reboot
 }
 
-sleep 5
-
 DEV='eth0'
 MAC=$(getMac "${DEV}")
 while [ "x${MAC}x" == "xx" ]; do
 	sleep 1
 	MAC=$(getMac "${DEV}")
 done
-
 echo Found hardware address "${MAC}".
 
 IP=$(getIp4 "${DEV}")
@@ -38,10 +36,9 @@ while [ "x${IP}x" == "xx" ]; do
 	sleep 1
 	IP=$(getIp4 "${DEV}")
 done
-
 echo Found IP address "${IP}".
 
-ip route add default via ${IP}
+#ip route add default via ${IP}
 
 FILE="/root/profile"
 GW=$(getGw "${DEV}")
@@ -49,7 +46,6 @@ while [ "x${GW}x" == "xx" ]; do
 	sleep 1
 	GW=$(getGw "${DEV}")
 done
-
 echo Found gateway "${GW}".
 
 getProfile "${GW}" "${MAC}" "${FILE}"
@@ -57,8 +53,8 @@ while [ ! -e "${FILE}" ]; do
 	sleep 1
 	getProfile "${GW}" "${MAC}" "${FILE}"
 done
-
 echo Loading iolite-build profile.
+
 . "${FILE}"
 
 /bin/cat <<eof >/etc/hostname
@@ -78,7 +74,8 @@ else
 fi
 
 echo Next step: Format disks
-DISKS=$(echo "${DISKLAYOUT}" | jq -r '.[].device')
+LAYOUT=$(echo "${DISKLAYOUT}" | jq '.layout')
+DISKS=$(echo "${LAYOUT}" | jq -r '.[] | keys[0]')
 
 # Check disks present
 for DISK in ${DISKS}; do
@@ -91,17 +88,83 @@ for DISK in ${DISKS}; do
 done
 echo All disks present.
 
-# Format disks.
+# Label disks and create partitions.
 for DISK in ${DISKS}; do
-	VDA_PARTS=$(echo ${DISKLAYOUT} | jq -r '[.[] | select(.device == "'${DISK}'") | .parts[]]')
-	LEN=$(echo $VDA_PARTS | jq 'length')
-	for I in $(seq 0 $((${LEN}-1))); do
-		#PART=$(echo $VDA_PARTS | jq '.['${I}']')
-		MOUNT=$(echo $VDA_PARTS | jq -r '.['${I}'].mount')
-		SIZE=$(echo $VDA_PARTS | jq -r '.['${I}'].size')
-		FS=$(echo $VDA_PARTS | jq -r '.['${I}'].fs')
-		echo mount $MOUNT size $SIZE fs $FS
-	done
+	PT=$(echo $LAYOUT | jq -r "add | .${DISK}" | base64 -d)
+	echo ${PT} | sfdisk "/dev/${DISK}"
+done
+
+
+
+
+TARGET_DISK="/dev/sdb"
+MOUNT_POINT="/mnt/min_linux"
+
+# 1. Partition the disk (MBR/Legacy boot format)
+echo 'type=83, bootable' | sudo sfdisk "$TARGET_DISK"
+
+# 2. Format the new partition
+sudo mkfs.ext4 "${TARGET_DISK}1"
+sudo mkdir -p "$MOUNT_POINT"
+sudo mount "${TARGET_DISK}1" "$MOUNT_POINT"
+
+# 3. Copy Kernel and Filesystem to the disk
+sudo mkdir -p "$MOUNT_POINT/boot/grub"
+sudo cp ~/minimal_linux/vmlinuz "$MOUNT_POINT/boot/vmlinuz"
+sudo cp ~/minimal_linux/initramfs.cpio.gz "$MOUNT_POINT/boot/initramfs.cpio.gz"
+
+# 4. Script the GRUB Bootloader configuration
+sudo cat << 'EOF' | sudo tee "$MOUNT_POINT/boot/grub/grub.cfg"
+set default=0
+set timeout=5
+
+menuentry "Minimal Custom Linux" {
+    linux /boot/vmlinuz rdinit=/init console=tty1
+    initrd /boot/initramfs.cpio.gz
+}
+EOF
+
+# 5. Install GRUB to the disk Master Boot Record (MBR)
+sudo grub-install --target=i386-pc --boot-directory="$MOUNT_POINT/boot" "$TARGET_DISK"
+
+# 6. Cleanup
+sudo umount "$MOUNT_POINT"
+echo "Deployment complete! Boot from $TARGET_DISK to test your OS."
+
+rebootSystem
+
+
+
+
+#❯ sudo Repositories/boot_iolite/tinypxe/source/initramfs/usr/bin/sfdisk -d /dev/nvme0n1
+#label: gpt
+#label-id: A1610265-5464-41B9-B0B2-0DA836BD0525
+#device: /dev/nvme0n1
+#unit: sectors
+#first-lba: 34
+#last-lba: 4000797326
+#sector-size: 512
+#
+#/dev/nvme0n1p1 : start=        2048, size=     1021952, type=C12A7328-F81F-11D2-BA4B-00A0C93EC93B, uuid=E2CA5109-BAEB-4727-89EB-6F91655BEA3C, name="linux-efi"
+#/dev/nvme0n1p2 : start=     1024000, size=     2048000, type=BC13C2FF-59E6-4262-A352-B275FD6F7172, uuid=877358FD-80CB-4177-9647-1424C6653071, name="linux-boot"
+#/dev/nvme0n1p3 : start=     3072000, size=  3997724672, type=0FC63DAF-8483-4772-8E79-3D69D8477DE4, uuid=21E47A78-9835-473F-B596-888A875DF17C, name="linux-root"
+
+#TARGET_DEV="/dev/sdb"
+#
+#sudo mkfs.vfat -F 32 "${TARGET_DEV}1"
+#sudo mkfs.ext4 -F "${TARGET_DEV}2"
+
+## 1. Wipe and create a MBR partition table with 1 bootable partition using sfdisk
+#sudo sfdisk "$TARGET_DEV" <<EOF
+#label: dos
+#type=83, bootable
+#EOF
+#
+# 2. Format the single partition
+#sudo mkfs.ext4 -F "${TARGET_DEV}1"
+#
+#echo "Legacy MBR Partitioning Complete!"
+#
 
 	#echo 
 
@@ -111,7 +174,7 @@ for DISK in ${DISKS}; do
 
 #<<<$DISKLAYOUT jq -r '.[] | select(.device == "vda") | .parts'
 
-done
+#done
 
 # disks
 #<<<$DISKLAYOUT jq -r '.[].device'
@@ -133,5 +196,3 @@ done
 # * don't even need package manager at this point
 # * suppose we can optionally add a package manager
 # The rest can be done with Ansible
-
-rebootSystem
